{{- if .Values.ingress.enabled }}
# Ingress: define regras de roteamento HTTP/HTTPS
# O AWS Load Balancer Controller converte isso em um ALB (Application Load Balancer)
# Annotations em values.yaml controlam configuração do ALB (internet-facing, target-type, etc)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frm-user-api.fullname" . }}
  labels: {{- include "frm-user-api.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "frm-user-api.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
{{- end }}
