{{- if .Values.serviceAccount.create }}
# ServiceAccount: identidade Kubernetes para os pods
# Associado a uma IAM Role via IRSA (criada pelo eksctl no workflow)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "farm-registry-api.serviceAccountName" . }}
  labels:
    {{- include "farm-registry-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
